GOOGLE_CREDENTIALS = """
{
  "type": "service_account",
  "project_id": "hindi-video-analytics",
  "private_key_id": "xxxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\nxxxx\n-----END PRIVATE KEY-----\n",
  "client_email": "streamlit-app-access@hindi-video-analytics.iam.gserviceaccount.com",
  ...
}
"""
GOOGLE_PROJECT_ID = "hindi-video-analytics"
